### ISSUE TITLE
Add passing test for poroelastic assembly.

### ISSUE THREAD

**Issue by lsawade** [PrincetonUniversity/SPECFEMPP#768]
## Task description

```yaml

  - name : "Test 9: Homogeneous Poroelastic Isotropic Material (P_SV wave)"
    description: >
      Testing the reading of a homogeneous poroelastic isotropic material.
    config:
      nproc : 1
      elastic_wave: "P_SV"
    databases:
      mesh : "data/mesh/homogeneous_poroelastic_isotropic/database.bin"
      sources : "data/mesh/homogeneous_poroelastic_isotropic/sources.yaml"
      stations : "data/mesh/homogeneous_poroelastic_isotropic/STATIONS"
    suffix: "homogeneous_poroelastic_isotropic_P_SV"
```

was ***not*** added to the `test_config.yaml` so it's not running. I checked adding it and it fails:

```
- Test: Test 9: Homogeneous Poroelastic Isotropic Material (P_SV wave)
- Error: 
         Error in function check_compute_to_mesh
         Error at ispec = 0, iz = 0, ix = 0, iprop = 0
         Expected:              phi = 0.1
                rho_s = 2650
                rho_f = 880
                tortuosity = 2
                mu_G = 5.1e+09
                H_Biot = 1.71614e+10
                C_Biot = 3.57278e+09
                M_Biot = 1.67646e+10
                Kxx = 1e-09
                Kzz = 1e-09
                Kxz = 0
                eta = 0

         Got:           phi = 10.5
                rho_s = 10.5
                rho_f = 10.5
                tortuosity = 10.5
                mu_G = 10.5
                H_Biot = 10.5
                C_Biot = 10.5
                M_Biot = 10.5
                Kxx = 10.5
                Kzz = 10.5
                Kxz = 10.5
                eta = 10.5
```

## Acceptance criteria
- [ ] tests pass
